# Generated by Django 5.2.3 on 2025-09-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumos',
            fields=[
                ('id_consumo', models.AutoField(db_column='ID_CONSUMO', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='CANTIDAD')),
            ],
            options={
                'db_table': 'consumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id_cuenta', models.AutoField(db_column='ID_CUENTA', primary_key=True, serialize=False)),
                ('noches', models.IntegerField(db_column='NOCHES')),
                ('total', models.DecimalField(blank=True, db_column='TOTAL', decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'cuentas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id_descuento', models.AutoField(db_column='ID_DESCUENTO', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_column='FECHA_INICIO')),
                ('fecha_fin', models.DateField(db_column='FECHA_FIN')),
                ('descuento', models.DecimalField(db_column='DESCUENTO', decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'descuentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distribuidores',
            fields=[
                ('id_distribuidor', models.AutoField(db_column='ID_DISTRIBUIDOR', primary_key=True, serialize=False)),
                ('marca', models.CharField(db_column='MARCA', max_length=50)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=50, unique=True)),
                ('email', models.CharField(db_column='EMAIL', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'distribuidores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id_habitacion', models.AutoField(db_column='ID_HABITACION', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(db_column='NUMERO', unique=True)),
                ('piso', models.IntegerField(db_column='PISO')),
                ('ocupado', models.IntegerField(blank=True, db_column='OCUPADO', null=True)),
            ],
            options={
                'db_table': 'habitaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Huespedes',
            fields=[
                ('id_huesped', models.AutoField(db_column='ID_HUESPED', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
                ('pr_apellido', models.CharField(db_column='PR_APELLIDO', max_length=50)),
                ('se_apellido', models.CharField(blank=True, db_column='SE_APELLIDO', max_length=50, null=True)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=50, unique=True)),
                ('email', models.CharField(db_column='EMAIL', max_length=50, unique=True)),
                ('edad', models.IntegerField(db_column='EDAD')),
            ],
            options={
                'db_table': 'huespedes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('id_inventario', models.AutoField(db_column='ID_INVENTARIO', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='CANTIDAD')),
            ],
            options={
                'db_table': 'inventarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_PRODUCTO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
                ('marca', models.CharField(db_column='MARCA', max_length=50)),
                ('costo', models.DecimalField(db_column='COSTO', decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rerestaurantes',
            fields=[
                ('id_restaurant', models.AutoField(db_column='ID_RESTAURANT', primary_key=True, serialize=False)),
                ('personas', models.IntegerField(db_column='PERSONAS')),
                ('fecha_hora', models.DateTimeField(db_column='FECHA_HORA')),
                ('activa', models.IntegerField(db_column='ACTIVA')),
            ],
            options={
                'db_table': 'rerestaurantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(db_column='ID_RESERVA', primary_key=True, serialize=False)),
                ('fecha_llegada', models.DateTimeField(db_column='FECHA_LLEGADA')),
                ('fecha_salida', models.DateTimeField(db_column='FECHA_SALIDA')),
                ('cantidad_a', models.IntegerField(db_column='CANTIDAD_A')),
                ('cantidad_n', models.IntegerField(db_column='CANTIDAD_N')),
                ('metodo_pago', models.CharField(blank=True, db_column='METODO_PAGO', max_length=8, null=True)),
                ('activa', models.IntegerField(db_column='ACTIVA')),
            ],
            options={
                'db_table': 'reservas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id_rest', models.AutoField(db_column='ID_REST', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id_staff', models.AutoField(db_column='ID_STAFF', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
                ('pr_apellido', models.CharField(db_column='PR_APELLIDO', max_length=50)),
                ('se_apellido', models.CharField(blank=True, db_column='SE_APELLIDO', max_length=50, null=True)),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=50, unique=True)),
                ('email', models.CharField(db_column='EMAIL', max_length=50, unique=True)),
                ('edad', models.IntegerField(db_column='EDAD')),
                ('area_trabajo', models.CharField(blank=True, db_column='AREA_TRABAJO', max_length=19, null=True)),
                ('salario', models.DecimalField(db_column='SALARIO', decimal_places=2, max_digits=8)),
                ('turno', models.CharField(blank=True, db_column='TURNO', max_length=10, null=True)),
            ],
            options={
                'db_table': 'staffs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id_tipo', models.AutoField(db_column='ID_TIPO', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='TIPO', max_length=8, null=True)),
                ('cama', models.IntegerField(db_column='CAMA')),
                ('baños', models.IntegerField(db_column='BAÑOS')),
                ('capacidad_a', models.IntegerField(db_column='CAPACIDAD_A')),
                ('capacidad_n', models.IntegerField(db_column='CAPACIDAD_N')),
                ('cocineta', models.IntegerField(db_column='COCINETA')),
                ('televisor', models.IntegerField(db_column='TELEVISOR')),
                ('vista', models.CharField(blank=True, db_column='VISTA', max_length=7, null=True)),
                ('precio', models.DecimalField(db_column='PRECIO', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'tipos',
                'managed': False,
            },
        ),
    ]
