# Generated by Django 5.2.3 on 2025-09-30 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trivago', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HuespedCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('huesped', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='trivago.huespedes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='huesped_cuenta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta de Huésped',
                'verbose_name_plural': 'Cuentas de Huéspedes',
            },
        ),
    ]
